package org.aminesidki.test.dto;

import java.io.Serializable;
import java.time.LocalDate;

/**
* Dto for {@link org.aminesidki.test.entity.Department }
*/
public record DepartmentDto (
    Long id,
    String name,
    String building,
    LocalDate establishedDate
) implements Serializable {}

//Generated by Sprout