package org.aminesidki.test.dto;

import java.io.Serializable;

/**
* Dto for {@link org.aminesidki.test.entity.Doctor }
*/
public record DoctorDto (
    Long id,
    String fullName,
    String specialization,
    Long department
) implements Serializable {}

//Generated by Sprout