package org.aminesidki.test.dto;

import java.io.Serializable;
import java.util.UUID;

/**
* Dto for {@link org.aminesidki.test.entity.MedicalRecord }
*/
public record MedicalRecordDto (
    UUID recordUuid,
    String diagnosis,
    String treatmentPlan,
    Long patient
) implements Serializable {}

//Generated by Sprout