package org.aminesidki.test.dto;

import java.io.Serializable;
import java.util.List;

/**
* Dto for {@link org.aminesidki.test.entity.Patient }
*/
public record PatientDto (
    Long id,
    String name,
    String bloodType,
    List<Long> primaryDoctors
) implements Serializable {}

//Generated by Sprout