package org.aminesidki.test.projection;

import java.io.Serializable;
import java.time.LocalDate;

/**
* Projection for {@link org.aminesidki.test.entity.Department }
*/
public record DepartmentProjection (
    Long id,
    String name
) implements Serializable {}

//Generated by Sprout