package org.aminesidki.test.repository;

import org.aminesidki.test.entity.Department;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
* Repository for {@link org.aminesidki.test.entity.Department }
*/
@Repository
public interface DepartmentRepository extends JpaRepository<Department, Long> {}

//Generated by Sprout