package org.aminesidki.test.repository;

import org.aminesidki.test.entity.Doctor;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
* Repository for {@link org.aminesidki.test.entity.Doctor }
*/
@Repository
public interface DoctorRepository extends JpaRepository<Doctor, Long> {}

//Generated by Sprout