package org.aminesidki.test.repository;

import org.aminesidki.test.entity.MedicalRecord;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.UUID;

/**
* Repository for {@link org.aminesidki.test.entity.MedicalRecord }
*/
@Repository
public interface MedicalRecordRepository extends JpaRepository<MedicalRecord, UUID> {}

//Generated by Sprout