package org.aminesidki.test.repository;

import org.aminesidki.test.entity.Patient;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;


/**
* Repository for {@link org.aminesidki.test.entity.Patient }
*/
@Repository
public interface PatientRepository extends JpaRepository<Patient, Long> {}

//Generated by Sprout