package org.aminesidki.test.mapper;

import org.aminesidki.test.entity.Department;
import org.aminesidki.test.projection.DepartmentProjection;
import org.aminesidki.test.dto.DepartmentDto;
import org.mapstruct.Mapper;

import java.time.LocalDate;

/**
* Mapper for {@link org.aminesidki.test.entity.Department }
*/
@Mapper(componentModel = "spring")
public abstract class DepartmentMapper {

    //Map to DTO
    public abstract DepartmentDto toDto(Department entity);
    public abstract DepartmentProjection toProjection(Department entity);
    //Map to Entity
    public abstract Department toEntity(DepartmentDto dto);

}

//Generated by Sprout