package org.aminesidki.test.mapper;

import org.aminesidki.test.entity.Doctor;
import org.aminesidki.test.dto.DoctorDto;
import org.mapstruct.Mapper;

import org.aminesidki.test.entity.Department;
import org.aminesidki.test.repository.DepartmentRepository;

/**
* Mapper for {@link org.aminesidki.test.entity.Doctor }
*/
@Mapper(componentModel = "spring")
public abstract class DoctorMapper {

    private DepartmentRepository departmentRepo ;

    //Map to DTO
    public abstract DoctorDto toDto(Doctor entity);
    //Map to Entity
    public abstract Doctor toEntity(DoctorDto dto);

    public Department mapIdToDepartment(Long id){
        if(id == null){
            return null;
        }
        return departmentRepo.findById(id).orElse(null);
    }

    public Long mapDepartmentToId(Department entity){
        if(entity == null){
            return null;
        }
        return entity.getId();
    }

}

//Generated by Sprout