package org.aminesidki.test.mapper;

import org.aminesidki.test.entity.MedicalRecord;
import org.aminesidki.test.dto.MedicalRecordDto;
import org.mapstruct.Mapper;

import org.aminesidki.test.repository.PatientRepository;
import java.util.UUID;
import org.aminesidki.test.entity.Patient;

/**
* Mapper for {@link org.aminesidki.test.entity.MedicalRecord }
*/
@Mapper(componentModel = "spring")
public abstract class MedicalRecordMapper {

    private PatientRepository patientRepo ;

    //Map to DTO
    public abstract MedicalRecordDto toDto(MedicalRecord entity);
    //Map to Entity
    public abstract MedicalRecord toEntity(MedicalRecordDto dto);

    public Patient mapIdToPatient(Long id){
        if(id == null){
            return null;
        }
        return patientRepo.findById(id).orElse(null);
    }

    public Long mapPatientToId(Patient entity){
        if(entity == null){
            return null;
        }
        return entity.getId();
    }

}

//Generated by Sprout