package org.aminesidki.test.mapper;

import org.aminesidki.test.entity.Patient;
import org.aminesidki.test.dto.PatientDto;
import org.mapstruct.Mapper;

import java.util.List;
import org.aminesidki.test.repository.DoctorRepository;
import org.aminesidki.test.entity.Doctor;

/**
* Mapper for {@link org.aminesidki.test.entity.Patient }
*/
@Mapper(componentModel = "spring")
public abstract class PatientMapper {

    private DoctorRepository doctorRepo ;

    //Map to DTO
    public abstract PatientDto toDto(Patient entity);
    //Map to Entity
    public abstract Patient toEntity(PatientDto dto);

    public List<Doctor> mapIdToDoctors(List<Long> ids){
        if(ids == null){
            return null;
        }
        return doctorRepo.findAllById(ids);
    }

    public List<Long> mapDoctorsToIds(List<Doctor> entities){
        if(entities == null){
            return null;
        }
        return entities.stream().map(e -> e.getId()).toList();
    }

}

//Generated by Sprout