package org.aminesidki.test.service;

import org.aminesidki.test.entity.Department;
import org.aminesidki.test.projection.DepartmentProjection;
import org.aminesidki.test.dto.DepartmentDto;
import org.aminesidki.test.exception.DepartmentException;
import org.aminesidki.test.mapper.DepartmentMapper;
import org.aminesidki.test.repository.DepartmentRepository;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;


@RequiredArgsConstructor
@Transactional
@Service
public class DepartmentService{
    private final DepartmentRepository departmentRepository;
    private final DepartmentMapper departmentMapper;

    @Transactional(readOnly = true)
    public List<DepartmentProjection> findAll() {
        return departmentRepository.findAll().stream()
                .map(departmentMapper::toProjection)
                .collect(Collectors.toList());
    }

    @Transactional(readOnly = true)
    public DepartmentDto findById(Long id) {
        return departmentRepository.findById(id)
                .map(departmentMapper::toDto)
                .orElseThrow(() -> new DepartmentException("Department not found with id: " + id));
    }


    public DepartmentDto save(DepartmentDto dto) {
        Department entity = departmentMapper.toEntity(dto);
        return departmentMapper.toDto(departmentRepository.save(entity));
    }

    public DepartmentDto update(DepartmentDto dto) {
        if (!departmentRepository.existsById(dto.id())) {
            throw new DepartmentException("Cannot update: Department not found with id: " + dto.id());
        }

        Department entity = departmentMapper.toEntity(dto);
        return departmentMapper.toDto(departmentRepository.save(entity));
    }

    public void delete(Long id) {
        if (!departmentRepository.existsById(id)) {
            throw new DepartmentException("Cannot delete: Department not found with id: " + id);
        }
        departmentRepository.deleteById(id);
    }
}

//Generated by Sprout