package org.aminesidki.test.service;

import org.aminesidki.test.entity.Doctor;
import org.aminesidki.test.dto.DoctorDto;
import org.aminesidki.test.exception.DoctorException;
import org.aminesidki.test.mapper.DoctorMapper;
import org.aminesidki.test.repository.DoctorRepository;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;


@RequiredArgsConstructor
@Transactional
@Service
public class DoctorService{
    private final DoctorRepository doctorRepository;
    private final DoctorMapper doctorMapper;

    @Transactional(readOnly = true)
    public List<DoctorDto> findAll() {
        return doctorRepository.findAll().stream()
                .map(doctorMapper::toDto)
                .collect(Collectors.toList());
    }

    @Transactional(readOnly = true)
    public DoctorDto findById(Long id) {
        return doctorRepository.findById(id)
                .map(doctorMapper::toDto)
                .orElseThrow(() -> new DoctorException("Doctor not found with id: " + id));
    }


    public DoctorDto save(DoctorDto dto) {
        Doctor entity = doctorMapper.toEntity(dto);
        return doctorMapper.toDto(doctorRepository.save(entity));
    }

    public DoctorDto update(DoctorDto dto) {
        if (!doctorRepository.existsById(dto.id())) {
            throw new DoctorException("Cannot update: Doctor not found with id: " + dto.id());
        }

        Doctor entity = doctorMapper.toEntity(dto);
        return doctorMapper.toDto(doctorRepository.save(entity));
    }

    public void delete(Long id) {
        if (!doctorRepository.existsById(id)) {
            throw new DoctorException("Cannot delete: Doctor not found with id: " + id);
        }
        doctorRepository.deleteById(id);
    }
}

//Generated by Sprout