package org.aminesidki.test.service;

import org.aminesidki.test.entity.MedicalRecord;
import org.aminesidki.test.dto.MedicalRecordDto;
import org.aminesidki.test.exception.MedicalRecordException;
import org.aminesidki.test.mapper.MedicalRecordMapper;
import org.aminesidki.test.repository.MedicalRecordRepository;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

import java.util.UUID;

@RequiredArgsConstructor
@Transactional
@Service
public class MedicalRecordService{
    private final MedicalRecordRepository medicalRecordRepository;
    private final MedicalRecordMapper medicalRecordMapper;

    @Transactional(readOnly = true)
    public List<MedicalRecordDto> findAll() {
        return medicalRecordRepository.findAll().stream()
                .map(medicalRecordMapper::toDto)
                .collect(Collectors.toList());
    }

    @Transactional(readOnly = true)
    public MedicalRecordDto findById(UUID id) {
        return medicalRecordRepository.findById(id)
                .map(medicalRecordMapper::toDto)
                .orElseThrow(() -> new MedicalRecordException("MedicalRecord not found with id: " + id));
    }


    public MedicalRecordDto save(MedicalRecordDto dto) {
        MedicalRecord entity = medicalRecordMapper.toEntity(dto);
        return medicalRecordMapper.toDto(medicalRecordRepository.save(entity));
    }

    public MedicalRecordDto update(MedicalRecordDto dto) {
        if (!medicalRecordRepository.existsById(dto.recordUuid())) {
            throw new MedicalRecordException("Cannot update: MedicalRecord not found with id: " + dto.recordUuid());
        }

        MedicalRecord entity = medicalRecordMapper.toEntity(dto);
        return medicalRecordMapper.toDto(medicalRecordRepository.save(entity));
    }

    public void delete(UUID id) {
        if (!medicalRecordRepository.existsById(id)) {
            throw new MedicalRecordException("Cannot delete: MedicalRecord not found with id: " + id);
        }
        medicalRecordRepository.deleteById(id);
    }
}

//Generated by Sprout