package org.aminesidki.test.service;

import org.aminesidki.test.entity.Patient;
import org.aminesidki.test.dto.PatientDto;
import org.aminesidki.test.exception.PatientException;
import org.aminesidki.test.mapper.PatientMapper;
import org.aminesidki.test.repository.PatientRepository;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;


@RequiredArgsConstructor
@Transactional
@Service
public class PatientService{
    private final PatientRepository patientRepository;
    private final PatientMapper patientMapper;

    @Transactional(readOnly = true)
    public List<PatientDto> findAll() {
        return patientRepository.findAll().stream()
                .map(patientMapper::toDto)
                .collect(Collectors.toList());
    }

    @Transactional(readOnly = true)
    public PatientDto findById(Long id) {
        return patientRepository.findById(id)
                .map(patientMapper::toDto)
                .orElseThrow(() -> new PatientException("Patient not found with id: " + id));
    }


    public PatientDto save(PatientDto dto) {
        Patient entity = patientMapper.toEntity(dto);
        return patientMapper.toDto(patientRepository.save(entity));
    }

    public PatientDto update(PatientDto dto) {
        if (!patientRepository.existsById(dto.id())) {
            throw new PatientException("Cannot update: Patient not found with id: " + dto.id());
        }

        Patient entity = patientMapper.toEntity(dto);
        return patientMapper.toDto(patientRepository.save(entity));
    }

    public void delete(Long id) {
        if (!patientRepository.existsById(id)) {
            throw new PatientException("Cannot delete: Patient not found with id: " + id);
        }
        patientRepository.deleteById(id);
    }
}

//Generated by Sprout