package org.aminesidki.test.controller;
import org.aminesidki.test.projection.DepartmentProjection;
import org.aminesidki.test.dto.DepartmentDto;
import org.aminesidki.test.service.DepartmentService;

import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RequiredArgsConstructor
@RestController
@RequestMapping("/api/v1/department")
public class DepartmentController{
    private final DepartmentService departmentService;

    @GetMapping
    public List<DepartmentProjection> getAll() {
        return departmentService.findAll();
    }

    @GetMapping("/{id}")
    public DepartmentDto getById(@PathVariable Long id) {
        return departmentService.findById(id);
    }

    @PostMapping
    public DepartmentDto save(@Valid @RequestBody DepartmentDto dto) {
        return departmentService.save(dto);
    }

    @PutMapping
    public DepartmentDto update(@Valid @RequestBody DepartmentDto dto) {
        return departmentService.update(dto);
    }

    @DeleteMapping("/{id}")
    public void delete(@PathVariable Long id) {
        departmentService.delete(id);
    }
}

//Generated by Sprout