package org.aminesidki.test.controller;
import org.aminesidki.test.dto.DoctorDto;
import org.aminesidki.test.service.DoctorService;

import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RequiredArgsConstructor
@RestController
@RequestMapping("/api/v1/doctor")
public class DoctorController{
    private final DoctorService doctorService;

    @GetMapping
    public List<DoctorDto> getAll() {
        return doctorService.findAll();
    }

    @GetMapping("/{id}")
    public DoctorDto getById(@PathVariable Long id) {
        return doctorService.findById(id);
    }

    @PostMapping
    public DoctorDto save(@Valid @RequestBody DoctorDto dto) {
        return doctorService.save(dto);
    }

    @PutMapping
    public DoctorDto update(@Valid @RequestBody DoctorDto dto) {
        return doctorService.update(dto);
    }

    @DeleteMapping("/{id}")
    public void delete(@PathVariable Long id) {
        doctorService.delete(id);
    }
}

//Generated by Sprout