package org.aminesidki.test.controller;
import org.aminesidki.test.dto.MedicalRecordDto;
import org.aminesidki.test.service.MedicalRecordService;

import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

@RequiredArgsConstructor
@RestController
@RequestMapping("/api/v1/medicalRecord")
public class MedicalRecordController{
    private final MedicalRecordService medicalRecordService;

    @GetMapping
    public List<MedicalRecordDto> getAll() {
        return medicalRecordService.findAll();
    }

    @GetMapping("/{id}")
    public MedicalRecordDto getById(@PathVariable UUID id) {
        return medicalRecordService.findById(id);
    }

    @PostMapping
    public MedicalRecordDto save(@Valid @RequestBody MedicalRecordDto dto) {
        return medicalRecordService.save(dto);
    }

    @PutMapping
    public MedicalRecordDto update(@Valid @RequestBody MedicalRecordDto dto) {
        return medicalRecordService.update(dto);
    }

    @DeleteMapping("/{id}")
    public void delete(@PathVariable UUID id) {
        medicalRecordService.delete(id);
    }
}

//Generated by Sprout