package org.aminesidki.test.controller;
import org.aminesidki.test.dto.PatientDto;
import org.aminesidki.test.service.PatientService;

import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RequiredArgsConstructor
@RestController
@RequestMapping("/api/v1/patient")
public class PatientController{
    private final PatientService patientService;

    @GetMapping
    public List<PatientDto> getAll() {
        return patientService.findAll();
    }

    @GetMapping("/{id}")
    public PatientDto getById(@PathVariable Long id) {
        return patientService.findById(id);
    }

    @PostMapping
    public PatientDto save(@Valid @RequestBody PatientDto dto) {
        return patientService.save(dto);
    }

    @PutMapping
    public PatientDto update(@Valid @RequestBody PatientDto dto) {
        return patientService.update(dto);
    }

    @DeleteMapping("/{id}")
    public void delete(@PathVariable Long id) {
        patientService.delete(id);
    }
}

//Generated by Sprout